### ISSUE TITLE
Filter expression fields are undocumented

### ISSUE THREAD

**Issue by G-Goldstein** [googleapis/python-grafeas#48]
I'm using the filter functionality of `list_occurrences` to retrieve a subset of results by `resourceUrl`, and I want to start including other fields in the filters. The documentation [here ](https://github.com/googleapis/python-grafeas/blob/master/grafeas/grafeas_v1/types/grafeas.py) indicates that fields such as `note_name` can be used in filters, but no expected case-variant of `note_name` such as `noteName` or `NoteName` is valid in the filter, and any attempt to use it where `resourceUrl` worked gives me `google.api_core.exceptions.InvalidArgument: 400 Request contains an invalid argument.`

Curiously, `resourceUrl` is referred to everywhere else as `resource_uri`, including in the code, and the `resource_uri` property on the page linked above doesn't say that it can be used as a filter field. The only reason I know this is valid is because I've seen documentation that uses it. It seems as though there's some secret language used for filters that doesn't appear in the rest of the documentation, and I can't for the life of me track down any documentation or where it comes from, in either this project or the grafeas/grafeas project on which I'm assuming this is based. Is there anywhere I can find a complete list of filter fields that I can use?

I'm using `grafeas==1.0.1`, which was installed as a dependency for `google-cloud-containeranalysis==2.0.0`

**Comment by busunkim96** [comment]
Hi @G-Goldstein,

https://cloud.google.com/container-registry/docs/get-image-vulnerabilities#filtering describes different expressions, although I'm not sure the list is exhaustive.

The library documentation you see is generated from comments above the [source protos](https://github.com/googleapis/googleapis/blob/2db5725bf898b544a0cf951e1694d3b0fce5eda3/google/devtools/containeranalysis/v1beta1/grafeas/grafeas.proto#L190-L192) which define the API surface.

I've opened an issue on the Container Analysis team's issue tracker internally.

**Comment by dinagraves** [comment]
FWIW, `noteId` is a valid filter and would work in place of `note_name`.

**Comment by parthea** [comment]
Googlers see b/167572436

**Comment by engelke** [comment]
Bug has been filed.
