### ISSUE TITLE
FlakyBot does not appear to be correctly configured

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/python-grafeas#57]
Looking at the test failures in #56, and I see that tests unrelated to my PR are failing.  These are the exact kind of things I'd expect FlakyBot to be capturing, and filing P1 bugs for.  So we need to a.) investigate why the bot didn't pick this up and b.) get master green.

**Comment by busunkim96** [comment]
Fixed by https://github.com/googleapis/synthtool/pull/950
